### ISSUE TITLE
Recall and accuracy generate `NaN`s

### ISSUE THREAD

**Issue by pgronkievitz** [finloop/matlab-neural-networks#1]
https://github.com/finloop/matlab-neural-networks/blob/99075e94ebfe4d38544a3dd8eae7b5e5d69ee3aa/1-layer/Lab01.m#L74-L77

Those lines generate `NaN`s as `Y_Out_Final` can contain `0`s, so there's division by zero.

**Comment by finloop** [comment]
It's a simple fix. If `Y_Out_Final` contains only zeros, then accuracy should be `0.0` too.
